/* is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
int *
server_calculator_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static int  result;
	result=0;
	if(argp->n2==0 && argp->operator=='/'){
		printf("ERROR: cannot divide by 0; we will calculate this as 0\n");
		return &result;
	}
	switch(argp->operator){
			case '+': result= argp->n1+argp->n2;break;
			case '-': result= argp->n1-argp->n2;break;
			case '*': result= argp->n1*argp->n2;break;
			case '/': result= argp->n1/argp->n2;break;
	        case '^': result= 1;
                      for(int i =0 ; i < argp->n2; i++){
                          result *= argp->n1;
                      }
                      break; 
    }

	printf("Server calculated .. %d %c %d = %d\n",argp->n1,argp->operator, argp->n2,result);
	return &result;
}

